In [38]:
import itertools
import numpy as np

def det_is_zero(mat):
    #Checking if determinant is 0.
    return round(np.linalg.det(mat)) == 0

def rotations(mat):
    #Returning all the rotations of a matrix 
    mats = []
    m = mat.copy()
    for _ in range(4):
        mats.append(m)
        m = np.rot90(m)
    return mats

def canonical_form(mat):
    # Flatten each rotation and taking the lowest value tuple which can be compared against all the others in count_unique.
    forms = [tuple(r.flatten()) for r in rotations(mat)]
    return min(forms)

def count_unique(sum_ones):
    #Finding the determinants of the matrices unique up to rotation and how many have determinant 0.
    seen = {}
    for bits in itertools.product([0,1], repeat=9):
        if sum(bits) == sum_ones:
            M = np.array(bits).reshape(3,3)
            key = canonical_form(M)
            if key not in seen:
                seen[key] = M
    det_zero_reps = [M for M in seen.values() if det_is_zero(M)]

    total = len(seen)
    zero_det = len(det_zero_reps)
    nonzero_det = total - zero_det
    return total, zero_det, nonzero_det, det_zero_reps



# Case 1: ones go first (5 ones)
case_ones_first,a,b,c = count_unique(5)

# Case 2: zeros go first (4 ones)
case_zeros_first,d,e,f = count_unique(4)

print("Number of unique matrices with 1's going first is" ,case_ones_first)
print("Number of matrices with 0 determinant is",a)
print("Number of matrices with non-zero determinant is",b)
print("Number of unique matrices with 0's going first is",case_zeros_first)
print("Number of matrices with 0 determinant is",d)
print("Number of matrices with non-zero determinant is",e)

print("All the matrices from both cases with determinant 0:")

c,f


Number of unique matrices with 1's going first is 34
Number of matrices with 0 determinant is 15
Number of matrices with non-zero determinant is 19
Number of unique matrices with 0's going first is 34
Number of matrices with 0 determinant is 25
Number of matrices with non-zero determinant is 9
All the matrices from both cases with determinant 0:


([array([[0, 0, 0],
         [0, 1, 1],
         [1, 1, 1]]),
  array([[0, 0, 0],
         [1, 0, 1],
         [1, 1, 1]]),
  array([[0, 0, 0],
         [1, 1, 0],
         [1, 1, 1]]),
  array([[0, 0, 0],
         [1, 1, 1],
         [0, 1, 1]]),
  array([[0, 0, 0],
         [1, 1, 1],
         [1, 0, 1]]),
  array([[0, 0, 0],
         [1, 1, 1],
         [1, 1, 0]]),
  array([[0, 0, 1],
         [0, 0, 1],
         [1, 1, 1]]),
  array([[0, 0, 1],
         [1, 0, 1],
         [1, 0, 1]]),
  array([[0, 0, 1],
         [1, 1, 0],
         [1, 1, 0]]),
  array([[0, 0, 1],
         [1, 1, 1],
         [0, 0, 1]]),
  array([[0, 1, 0],
         [1, 0, 1],
         [1, 0, 1]]),
  array([[0, 1, 0],
         [1, 1, 1],
         [0, 1, 0]]),
  array([[0, 1, 1],
         [0, 0, 0],
         [1, 1, 1]]),
  array([[1, 0, 1],
         [0, 0, 0],
         [1, 1, 1]]),
  array([[1, 0, 1],
         [0, 1, 0],
         [1, 0, 1]])],
 [array([[0, 0, 0],
         [0, 0, 1],
         [1, 1, 1]]),
  array